### ISSUE TITLE
About WpfDemo

### ISSUE THREAD

**Issue by FoggyFinder** [fuszenecker/FSharpDemo#7]
In WpfDemo you use reference to library [FSharp.ViewModule](https://www.nuget.org/packages/FSharp.ViewModule.Core) , but not using its capabilities. May I ask why?

**Comment by fuszenecker** [comment]
It is just a demo, I just want to show that a WPF app can be created using F#.
Thanks for commenting the code.

**Comment by FoggyFinder** [comment]
Would you mind if I rewrite it with using FSharp.ViewModule?

**Comment by fuszenecker** [comment]
It would be great.
Many thanks :-)
